version: '1.0'

middleware : 
  path: /middleware
  setup_script_path: setup.sh
  start_script_path: run.sh
  description: "Fake ID Generator API"

services:
  name-service:
    path: /services/nameServices
    setup_script_path: setup.sh
    start_script_path: run.sh
    description: "Service de génération de prénoms et noms"

  gender-service:
    path: /services/genderServices
    setup_script_path: setup.sh
    start_script_path: run.sh
    description: "Service de détermination du genre"

  nationality-service:
    path: /services/nationalityServices
    setup_script_path: setup.sh
    start_script_path: run.sh
    description: "Service de détermination de la nationalité"

  birth-place-service:
    path: /services/birthPlaceServices
    setup_script_path: setup.sh
    start_script_path: run.sh
    description: "Service de génération d'un lieu de naissance"

  age-service:
    path: /services/ageServices
    setup_script_path: setup.sh
    start_script_path: run.sh
    description: "Service de génération d'âge"

  unique-id-service:
    path: /services/uniqueIDServices
    setup_script_path: setup.sh
    start_script_path: run.sh
    description: "Service de génération d'ID unique"

  face-generation-service:
    path: /services/faceServices
    setup_script_path: setup.sh
    start_script_path: run.sh
    description: "Service de génération de visages"
